config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :spaces do
    resources :bookings, only: [:new, :create, :index]
    # patch :update_max_availability, on: :member
  end
  resources :bookings, only: [:show, :edit, :update, :destroy]
  get '/profile',  to: 'profiles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :space
  validates :start_date, :end_date, presence: true
end

app/models/space.rb
class Space < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 3 }
  validates :max_capacity, presence: true, numericality: { only_integer: true }
  validates :price_per_day, presence: true, numericality: { only_integer: true }
  validates :user_id, presence: true
  validates :address, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spaces
  has_many :bookngs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @space = Space.find(params[:space_id])
    @bookings = Booking.where(space_id: params[:space_id])
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @space = Space.find(params[:space_id])
    @booking.user = current_user
    @booking.space = @space
    if @booking.save!
      redirect_to profile_path, notice: 'Booking successful!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to profile_path, notice: 'Booking was successfully updated.'
  end

  def destroy
    @booking.destroy
    redirect_to profile_path, notice: 'Booking was successfully destroyed.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:space_id, :start_date, :end_date, :number_of_persons, :confirmation)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user)
    @spaces = Space.where(user_id: current_user)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show
  # def update_max_availability
  #   @space = Space.find(params[:id])
  #   @booking = Booking.where
  # end
  def index
    @spaces = Space.geocoded
    # set_search_query
    unless params[:spaces].nil?
      if params[:spaces][:address].present?
        @spaces = Space.near(params[:spaces][:address], 20)
      else
        @spaces = Space.all
      end
      # if params[:spaces][:start_date].present?
      #   start_date = Date.parse(params[:spaces][:start_date])
      #   end_date = Date.parse(params[:spaces][:end_date])
      #   @spaces = filter_by_date(@spaces, start_date, end_date )
      # end
    end

    @markers = @spaces.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude,
        infoWindow: render_to_string(partial: "/shared/info_window", locals: { space: space }),
        image_url: helpers.asset_url('map_pin.png')
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    if @space.save!
      # redirect_to spaces_path(spaces: { address: '' })
      redirect_to profile_path, notice: 'Space created successfully!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @space.update(space_params)
      # redirect_to @space, notice: 'Space was successfully updated.'
      redirect_to profile_path, notice: 'Space was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @space.destroy
    # redirect_to spaces_path, notice: 'Space was successfully deleted.'
    redirect_to profile_path, notice: 'Space was successfully updated.'
  end

  private

  def set_space
    @space = Space.find(params[:id])
  end

  def space_params
    params.require(:space).permit(:name, :description, :address, :max_capacity, :price_per_day, :photo, :latitude, :longitude)
  end

  # def filter_by_date(spaces, start_date, end_date)
  #   selection = list_dates(start_date, end_date)
  # end

  # def list_dates(start_date, end_date)
  #   i = start_date
  #   list = []
  #   while i < end_date do
  #     list.push[i]
  #     i += 1
  #   end

  # end
  # def set_search_query
  #   unless params[:spaces].nil?

  #     unless params[:spaces][:start_date].nil?
  #       # unless params[:spaces][:start_date].empty?
  #       #   begin
  #       #     start_date = Date.parse(params[:spaces][:start_date])
  #       #     end_date = Date.parse(params[:spaces][:end_date])
  #       #   rescue ArgumentError

  #       #   end

  #         if (start_date.is_a?(Date) && end_date.is_a?(Date))
  #           @date_selected_spaces = Space.joins(:bookings).where.not('start_date > ? AND end_date < ?', start_date, end_date)
  #           @spaces = (@spaces.nil? ? Space.all : @spaces) - @date_selected_spaces

  #         end
  #       else
  #         @spaces = Space.all
  #       end
  #     else
  #       @spaces = Space.all
  #     end


  #     unless params[:spaces][:address].nil?
  #       unless params[:spaces][:address].empty?
  #         # @spaces = @spaces.near(params[:spaces][:address], 20)
  #         new = @spaces.select { |space| space.address == params[:spaces][:address] }
  #       end
  #     end

  #   else
  #     @spaces = Space.all
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div class="container mt-3 mb-5">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="form-login text-dark mt-3 mb-3 mx-n3">
        <%= simple_form_for [space, booking] do |f| %>
          <%= f.input :number_of_persons, collection: 1..60, selected: params[:spaces][:guests].to_i %>
          <%= f.input :start_date, as: :string, input_html: {value: params[:spaces][:start_date], class: "datepicker"} %>
          <%= f.input :end_date, as: :string, input_html: {value: params[:spaces][:end_date], class: "datepicker"} %>
          <%= f.submit "Book this space", class: "btn-submit bg-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container mt-3 mb-5">
  <div class="mt-1 d-flex justify-content-between align-items-center">
    <h3 class="text-left ml-5">Edit your booking</h3>
    <%= link_to "Back to profile", profile_path, class: "btn btn-success" %>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="form-login text-dark mt-3 mb-3">
        <%= simple_form_for @booking do |f| %>
        <%= f.input :number_of_persons %>
        <%= f.input :start_date, as: :string, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, input_html: {class: "datepicker"} %>
        <%= f.submit "Update", class: "btn-submit bg-success" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between mt-3 page-heading">
    <h3 class = "ml-4">Booking History for <strong><%= @space.name %></strong></h3>
    <%= link_to 'Back to my listings', profile_path, class: "btn btn-success" %>
  </div>
  <% if @bookings.any? %>
    <% @bookings.each do |booking| %>
      <div class="col-xs-12 col-sm-4">
        <div class="mx-3 my-3" >
          <div class="card-product">
            <div class="card-product-infos">
              <p>User: <%= "#{@space.user.first_name.capitalize}  #{@space.user.last_name.capitalize}" %></p>
              <p>From: <strong><%= booking.start_date %></strong> To: <strong><%= booking.end_date %></strong></p>
              <p>Booked for <strong><%= booking.number_of_persons %></strong> people</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p class="ml-4">There are no bookings for this space.</p>
  <% end %>
</div>
<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Space chaos</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div style="position: relative">

  <div class="banner">
    <div class="container_chaos">
      <h1>chaos</h1>
    </div>
    <div class="container_space">
      <h1>space</h1>
    </div>
</div>
</div>

<div class="form_container">
  <h3>Find a space near you</h3>
  <%= simple_form_for :spaces, url: spaces_path, method: "get" do |f| %>
    <%= f.input :address, as: :string, placeholder: 'Type in your city', label: false, required: true %>
    <%= f.label :guests, 'Number of people:' %>
    <%= f.input :guests, collection: 1..60, selected: 1, label: false %>
    <%= f.label :start_date, 'From:' %>
    <%= f.input :start_date, as: :string, label: false, input_html: {class: "datepicker"} %>
    <%= f.label :end_date, 'To:' %>
    <%= f.input :end_date, as: :string, label: false, input_html: {class: "datepicker"} %>
    <%= f.button :submit, "Go", class: "btn btn-success" %>
  <% end %>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <div class="mt-1 d-flex justify-content-end align-items-center">
    <%= link_to "Browse all spaces", spaces_path(spaces: {address: ''}), class: "btn btn-success" %>
  </div>
  <% if @bookings.any? %>
    <h3 class="text-left mt-3 mb-2 ml-4">My bookings</h3>
    <div>
      <% @bookings.each do |booking| %>
        <div class="col-xs-12 col-sm-4">
          <div class="mx-3 my-3" >
            <div class="card-product">
              <%if booking.space.photo? %>
                <%= cl_image_tag booking.space.photo, height: 700, width: 500, crop: :fill %>
              <% else %>
                <%= image_tag ("http://thespaces.com/wp-content/uploads/2017/02/electroposive-NYC-coworking-space.jpg") %>
              <% end %>
              <div class="card-product-infos">
                <p class="profile-card-name"><%= booking.space.name %></p>
                <p><%= booking.space.address %></p>
                <!-- <p>User: <%#= "#{booking.user.first_name.capitalize} #{booking.user.last_name.capitalize}" %></p> -->
                <p>From: <%= booking.start_date %></p>
                <p>To: <%= booking.end_date %></p>
                <p>Booked for <strong><%= booking.number_of_persons %></strong> people </p>
                <% if booking.confirmation == true %>
                  <p>Status: Confirmed</p>
                <% else %>
                  <p style='margin-bottom: 14px;'>Status: Pending</p>
                <% end %>
                <br>
                <%#= link_to "Update", edit_booking_path(booking), class: "btn btn-success mt-3" %>
                <%= link_to "Delete", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-sm btn-success mt-3" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <%# else %>
    <!-- <p>Sorry, we couldn't find any space that meets your criteria.</p> -->
  <% end %>
</div>


<div class="container">
  <% if @spaces.any? %>
    <h3 class="text-left mt-5 mb-2 ml-4">My listings</h3>
    <div>
      <% @spaces.each do |space| %>
        <div class="col-xs-12 col-sm-4">
          <div class="mx-3 my-3" >
            <div class="card-product">
              <%if space.photo? %>
                <%= cl_image_tag space.photo, height: 700, width: 500, crop: :fill %>
              <% else %>
                <%= image_tag ("http://thespaces.com/wp-content/uploads/2017/02/electroposive-NYC-coworking-space.jpg") %>
              <% end %>
              <div class="card-product-infos">
                <p class='profile-card-name'><%= space.name %></p>
                <p><%= space.address %></p>
                <p><%= space.price_per_day %>€</p>
                <p>Accomodates <%= space.max_capacity %> people</p>
                <%= link_to "View all bookings", space_bookings_path(space), class: "link_profile_bookings" %>
                <%= link_to "Update", edit_space_path(space), class: "btn-sm btn-success mr-2" %>
                <%= link_to "Delete", space_path(space), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-sm btn-success mr-2" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <%# else %>
    <!-- <p>You don't have any listings</p> -->
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github fa-sm"></i></a>
    <a href="#"><i class="fab fa-twitter fa-sm"></i></a>
    <a href="#"><i class="fab fa-instagram fa-sm"></i></a>
    <a href="#"><i class="fab fa-facebook fa-sm"></i></a>
    <a href="#"><i class="fab fa-linkedin fa-sm"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with aggression! <i class="fab fa-angrycreative fa-lg"></i>
  </div>
</div>

app/views/shared/_info_window.html.erb
<div class="info_color">
  <h2><%= space.name %></h2>
  <p><%= space.address %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo2.png" %>

    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
          <%= link_to "Home", root_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rent a space", new_space_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My bookings", profile_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "Action", "#", class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Rent a space", "#", class: "nav-link" %>
          </li>
          <li>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/spaces/edit.html.erb
<div class="container padded">
  <div class="mt-1 d-flex justify-content-between align-items-center">
    <h3 class="text-left mt-3 ml-5">Edit your space</h3>
    <%= link_to "Browse all spaces", spaces_path, class: "btn btn-success" %>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="form-login text-dark mt-3 mb-3">
        <%= simple_form_for @space do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :address %>
          <%= f.input :max_capacity %>
          <%= f.input :price_per_day %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "Submit", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/index.html.erb
<div class="form-results-page">
  <%= simple_form_for :spaces, url: spaces_path, method: "get" do |f| %>
    <%= f.label :address, 'City' %>
    <%# if  params[:spaces][:address].present? %>
      <%= f.input :address, as: :string, input_html: {value: params[:spaces][:address]}, label: false  %>
      <%= f.label :guests, 'Number of people:' %>
      <%= f.input :guests, collection: 1..60, selected: params[:spaces][:guests].to_i, label: false %>
      <%= f.label :start_date, 'From:' %>
      <%= f.input :start_date, as: :string, label: false, input_html: {value: params[:spaces][:start_date], class: "datepicker date_field"} %>
      <%= f.label :start_date, 'To:' %>
      <%= f.input :end_date, as: :string, label: false, input_html: {value: params[:spaces][:end_date], class: "datepicker date_field"} %>
    <%# end %>
    <%= f.button :submit, "Go", class: "btn btn-success" %>
  <% end %>
</div>

<div class="results-container" style="position: relative, max-height:73vh; width:100vw; bottom: 0; overflow: hidden">
  <div class="spaces-list" style="width: 50vw;
  height: 73vh; display: inline-block; position:absolute; left: 0; overflow: scroll">
    <% if @spaces.any? %>
      <% @spaces.each do |space| %>
        <div class="col-xs-12 col-sm-4">
          <div class="mx-3 my-3" >
            <div class="card-product relative">
              <%= link_to "", space_path(space, request.query_parameters), class:"link" %>
              <%if space.photo? %>
                <%= cl_image_tag space.photo %>
              <% else %>
                <%= image_tag ("http://thespaces.com/wp-content/uploads/2017/02/electroposive-NYC-coworking-space.jpg") %>
              <% end %>
              <div class="card-product-infos">
                <h2><%= space.name %></h2>
                <p><%= space.address %></p>
                <p><%= space.price_per_day%>€</p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>Sorry, we couldn't find any space that meets your criteria.</p>
    <% end %>
  </div>
  <div
  id="map"
  style="width: 50vw;
  height: 73vh; display: inline-block; position:absolute; right: 0"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/spaces/new.html.erb
<div class="container mt-3 mb-5">
  <div class="mt-1 d-flex justify-content-between align-items-center">
    <h3 class="text-left ml-5">Add your space</h3>
    <%= link_to "Browse all spaces", spaces_path(spaces: {address: ''}), class: "btn btn-success" %>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="form-login text-dark mt-3 mb-3">
        <%= simple_form_for @space do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :address %>
          <%= f.input :max_capacity %>
          <%= f.input :price_per_day %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "Submit", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/show.html.erb
<div class="card-show">
  <%= link_to "Browse all spaces", spaces_path(spaces: {address: ''}), class: "btn btn-success" %>
  <%if @space.photo? %>
    <%= cl_image_tag @space.photo %>
  <% else %>
    <%= image_tag ("http://thespaces.com/wp-content/uploads/2017/02/electroposive-NYC-coworking-space.jpg") %>
  <% end %>
  <h2 class="name"><%= @space.name %></h2>
  <h3 class="location"><%= @space.address %></h3>
  <p class="name"><%= @space.description %></p>
  <p style='font-weight: 600; font-size: 24px; color: #00FF97'><%= @space.price_per_day %>€/day</p>
  <!-- <div class="col-sm-12 col-md-6"> -->
  <div class="booking-form">
    <%= render "bookings/new", space: @space, booking: @booking %>
  </div>
</div>